### ISSUE TITLE
Core Solver - Few solver issues in Maya 2018

### ISSUE THREAD

**Issue by valmikchavan** [david-cattermole/mayaMatchMoveSolver#116]
Hey David,

Iam using maya2018 solver and noticed few issues, please have a look and let us know your thoughts.

OS : Linux
Maya :2019
Solver : 0.2.3

* Sometime solve wont work on first and last frame and if we go back again on 1st frame and solve again it works

* If we  have got the solve and we try to solve again  it  tends to make random translation and rotation channel to become static

* In lineup frame if model has the channel (rotation or translation )value is  0  we wont get the proper solve

Many thanks !

**Comment by david-cattermole** [comment]
Hello valmikchavan,

Thanks for reporting these! 

> Sometime solve wont work on first and last frame and if we go back again on 1st frame and solve again it works

What type of solves are you performing when this happens? Are you solving camera attributes or bundle attributes? Or rig controls?

> If we have got the solve and we try to solve again it tends to make random translation and rotation channel to become static
When you say "static", do you mean the values are solved almost static? Or are the keyframes on the attribute deleted?

Again, what type of solves are you performing when this happens? Are you solving camera attributes or bundle attributes? Or rig controls?

> In lineup frame if model has the channel (rotation or translation )value is 0 we wont get the proper solve
This issue might be related to issue #54, however I was not aware this is happening for translation values too.


Are there any non-NDA Maya scenes you can provide that replicate these bugs? I don't need plates, but i need all 3D nodes in the scene that replicate the issue. You can contact me offline if you need to.

**Comment by valmikchavan** [comment]
Hey David,

Thanks for the update,

Basically im trying to solve the head object Track, so im solving my face track markers and face mesh attribute together.

i am trying to get help from our developer here, if we are unable find solution we'll get back to you.

Thanks !

**Comment by david-cattermole** [comment]
Hello Valmik,

Have you or the developer found a solution to this issue?

If it's possible, I'd really like an example scene that reproduces the "first frame and last frame not solving" issue.

I'm working on a few different fixes and improvements to the solver engine which I hope will address these issues in v0.3.0, for example #72, #57 and #122.
I'd like to close this issue and keep any comments on those issue numbers.

Is that ok?

David

**Comment by david-cattermole** [comment]
I'm going to close this now. If I can get reproduction steps or an example Maya file, I can continue with this issue, otherwise v0.3.0 should try to address this type of problem.
