### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by arunmv91** [david-cattermole/mayaMatchMoveSolver#146]
Guys, please make it to work with mac as well.. I'm waiting since the initial release..

**Comment by david-cattermole** [comment]
Hello @arunmv91,

I understand the frustration however I do not have any Mac hardware to build and test with, and I cannot afford to buy hardware for this project. Apple has made it difficult to develop for a Mac without buying Mac hardware.
That is the primary reason for the lack of Mac support.

I will look into building and testing on Mac, and I will keep this Issue open in GitHub, until one day when I am able to develop on MacOS.

After doing some research, I can see that Maya 2016-2019 (the currently supported Maya versions) require different operating systems.
What version of Maya and MacOS are you running?

David

**Comment by arunmv91** [comment]
Thanks for the reply David, i'm running maya 2019.2 on mac os 10.15

**Comment by david-cattermole** [comment]
My current progress... for me to remember next time I come to this.

In a local build I have been able to build the mmSolver plug-in under MacOS X El Capitan 10.11 with Maya 2019.

I have needed to manually edit the `mmSolver.bundle` to find `libcminpack.1.dylib` using install_name_tool and explicitly changing the "rpath" - which not great at all.

Even after getting the plug-in to actually load, Maya does not automatically load mmSolver shelves and menus as it does on Linux and Windows. I think it's caused by the `MAYA_MODULE_PATH` being different somehow on MacOS X.

@arunmv91, Assuming I can work out all these problems, I will provide you with a plug-in for Maya 2019 which I'd like you to test and try to break. 

After that I will work on merging these changes back into the main line without affecting the Windows and Linux builds and write all the documentation. Then hopefully v0.3.7 will have a MacOS X build for both Maya 2018 and 2019. Maya 2016 and 2017 will not be supported, it's way too much work.

**Comment by david-cattermole** [comment]
Hello @arunmv91,

I have a version of mmSolver for use with Maya 2019 on MacOS.

You can download it here:
https://github.com/david-cattermole/mayaMatchMoveSolver/releases/tag/v0.3.7-beta.1

The install instructions are on the download page.

Please comment here with your results.

David

**Comment by arunmv91** [comment]
Hello David, Thank you for taking the effort to make this version, just now i got the time to try this out.. so far it’s working well. In macOS 10.15 there was this thing called “Gatekeeper” which kept preventing mmSolver to run. Had do disable it to get it working. Will let you know the progress..

**Comment by david-cattermole** [comment]
Thanks @arunmv91, this is good to hear.

I'll see what I can do about "Gatekeeper" - I'm guessing it's because it's not "authorised" by Apple.

Please do let me know if there are problems. 
Before I release the next version, I'll check in and see how it's going.

David

**Comment by david-cattermole** [comment]
Full MacOS support for Maya 2018 and 2019 is looking promising for release in v0.3.7.

Maya 2020 support is still lagging and is covered in #151.

@arunmv91 have you had any problems with the beta version I provided you?

**Comment by david-cattermole** [comment]
Hello @arunmv91, 

I have just released a "beta2" for MacOS.
https://github.com/david-cattermole/mayaMatchMoveSolver/releases/tag/v0.3.7

This new version contains all the latest features and bug fixes.
Please test it out and let me know how it goes.

I am intending to fully support MacOS in the v0.4.0 release.

David

**Comment by arunmv91** [comment]
Hello David, Sorry for the delayed response.. 
I have been using that beta version and it's working pretty well. i didn't find any issues so far..  

On Oct 16, 2020, at 9:19 AM, David Cattermole <notifications@github.com> wrote:


Full MacOS support for Maya 2018 and 2019 is looking promising for release in v0.3.7.

Maya 2020 support is still lagging and is covered in #151 <https://github.com/david-cattermole/mayaMatchMoveSolver/issues/151>.

@arunmv91 <https://github.com/arunmv91> have you had any problems with the beta version I provided you?

**Comment by arunmv91** [comment]
> Hello @arunmv91,
> 
> I have just released a "beta2" for MacOS.
> https://github.com/david-cattermole/mayaMatchMoveSolver/releases/tag/v0.3.7
> 
> This new version contains all the latest features and bug fixes.
> Please test it out and let me know how it goes.
> 
> I am intending to fully support MacOS in the v0.4.0 release.
> 
> David

**Comment by arunmv91** [comment]
Installing this now.. Thank you..

**Comment by arunmv91** [comment]
@david-cattermole maya is throwing in this error while opening mmsolver.
# Error: ImportError: file /Users/*****/Library/Preferences/Autodesk/maya/2019/modules/mayaMatchMoveSolver-0.3.7-beta2-maya2019-mac/python/mmSolver/ui/uiutils.py line 27: No module named Qt #

**Comment by david-cattermole** [comment]
Thanks for letting me know, @arunmv91.

I expect that should be a quick fix, I should be able to fix it and release in about 12 hours time.

David

**Comment by david-cattermole** [comment]
@arunmv91 I have updated the release with a `beta3`.

Can you please try to install the new beta3 version?

https://github.com/david-cattermole/mayaMatchMoveSolver/releases/tag/v0.3.7

**Comment by arunmv91** [comment]
Yes.. This is working fine.. Thanks.. :)

**Comment by david-cattermole** [comment]
Hello @arunmv91,

I found a bug in the Solver UI (for all OSs and Maya versions), and have released a new version:
https://github.com/david-cattermole/mayaMatchMoveSolver/releases/tag/v0.3.8

I have removed the "beta" status from this version, it's just v0.3.8.

I would recommend updating, if possible.

Enjoy and let me know if you have problems,
David

**Comment by arunmv91** [comment]
Ok david, i will install this.. 


Thanks,

**Comment by david-cattermole** [comment]
Hello @arunmv91,

Adding support for MacOS has taken a disproportionate amount of time for me compared to Linux and Windows.

I have decided that I will not be providing testing or binaries for MacOS starting with v0.4.0.

Unless there are a significant amount of users requesting MacOS support, I do not believe it's economical to spend as much time as I have on this.

I hope you can understand my reasoning,
David
