### ISSUE TITLE
Build mmSolver for Maya 2020

### ISSUE THREAD

**Issue by david-cattermole** [david-cattermole/mayaMatchMoveSolver#151]
### Feature
mmSolver is not compiled for Maya 2020, however users have requested the need for this.

Relates to some of the other build system changes that are required; #146 #148 #149, and #150.

### Software Versions

- mmSolver version: Latest version.

- Maya version: Maya 2020

- Operating System (OS): All Operating Systems.

**Comment by tlhommeperso** [comment]
hello there,
is there any ETA on this build ? wondering if getting the 2019 version installed in maya 2020 could work.
cheers
tl.

**Comment by david-cattermole** [comment]
Hello @tlhommeperso,

Currently no there isn't an ETA because I don't have the resources to use Maya 2020, however I'll bump this up the priority list and see what I can do about the resources issue.

David

**Comment by tlhommeperso** [comment]
hello thanks for your answer.
just loet me know if you need founding to buy a monthly maya 2020 licence
if that can fastn ethe process i would be happy to chip in !

**Comment by david-cattermole** [comment]
Hello @tlhommeperso,

In the next release I will be providing a Maya 2020 compiled plug-in.
There's still some work to be done, for testing and fixing any potential, but it should be ready in the next few weeks.

Also, unfortunately I will need to drop support for Maya 2016.

David

**Comment by david-cattermole** [comment]
The build for Maya 2020 seems to be working quite well now, on at least Windows (Linux is still to be tested). Unless something goes drastically wrong, I think we can consider this fixed.

Currently I am unable to provide a MacOS build for Maya 2020, that will hopefully change soon but I will track the problem in a new issue.

This build will be released with v0.3.13.

**Comment by david-cattermole** [comment]
@tlhommeperso v0.3.13 is now released:
https://github.com/david-cattermole/mayaMatchMoveSolver/releases/tag/v0.3.13

**Comment by tlhommeperso** [comment]
@david-cattermole amazing ! thank you for your quick turn around !
