### ISSUE TITLE
Allow Users to Disable the Auto-Adding Markers to the Active Collection

### ISSUE THREAD

**Issue by david-cattermole** [david-cattermole/mayaMatchMoveSolver#164]
### Problem / Feature
Users want to be able to disable (or enable) the feature from #138, so that newly created Markers are not added to the active Collection.

The ability to enable/disable automatically adding Markers to Collections is not a feature of Collections, or the Solver UI.
Instead the feature is determined at the basis of mmSolver.

This calls for a kind of "Preference option" that the user may want to change.
Other preferences may also exist in mmSolver and these should be documented and be settable as well.

### Software Versions

- mmSolver version: v0.3.8
- Maya version: All
- Operating System (OS): All

**Comment by david-cattermole** [comment]
Hello Etienne,

That's not a bad idea. I could add another drop-down box to the Load Markers UI which automatically adds the marker to the specified Collection.
By default the drop-down menu would use the active Collection.

I think it's still a good idea to have a preference that users can set, but this Loader Markers UI would override that option and place the marker into the specific Collection that was requested by the user.

What do you think?

David

**Comment by david-cattermole** [comment]
Hello @RodeoPerchaude,

I have added a User Preferences window, and an underlying user preferences library to control the behaviour of "Add New Markers To".

You can find the tool in the `mmSolver > General Tools > User Preferences...` shelf button.
![image](https://user-images.githubusercontent.com/891288/97525357-b8548f80-19fa-11eb-883a-a54cf5e57d00.png)

The window is currently quite empty except for the one preference:
![image](https://user-images.githubusercontent.com/891288/97525382-c4405180-19fa-11eb-8d29-8dfbf3d1c7bf.png)

This update will also temporarly disable "Add New Markers To" from running when using the Load Markers tool, even if the user preference has turned the option on. Users must manually apply the Markers to the collection of their choosing, until I can add a feature to the Load Markers UI to automate this.

This will be released in v0.3.9, hopefully this weekend.

David

**Comment by RodeoPerchaude** [comment]
Thanks a lot @david-cattermole .

I will definitely use this feature.

**Comment by david-cattermole** [comment]
This will be released shortly in v0.3.9.

Closing for now.
