### ISSUE TITLE
Raycastmarker current frame viewport pause

### ISSUE THREAD

**Issue by bpatchasaheb** [david-cattermole/mayaMatchMoveSolver#194]
While projecting markers on current frame, mmSolver is not supposed to pause the viewport so imageplane cache will not be cleared.

**Comment by david-cattermole** [comment]
Agreed, when ray-casting on a single frame, the viewport should not be disabled then immediately re-enabled.
Only when there are multiple frames to be ray-cast should the tool automatically disable the viewport.

**Comment by david-cattermole** [comment]
This has been fixed in f832bcd and has been merged into `develop_v0.3.x` and `develop` branches.

This will be released in the next version (v0.3.12).
