### ISSUE TITLE
Maya Tools - Change Rotation Order Tool

### ISSUE THREAD

**Issue by david-cattermole** [david-cattermole/mayaMatchMoveSolver#201]
### Feature
While animating an object changing the rotation order, without needing to animate everything, is sometimes necessary.

To do this, Morgan Loomis has a fantastic tool [ml_convertRotationOrder](http://morganloomis.com/tool/ml_convertRotationOrder/). I would like to integrate the (MIT licensed) code into mmSolver, or re-write a similar tool.

### Usage Steps

We can use the UI like this:

1. Select object
2. Animate the object with default XYZ rotation order.
3. Select transform node.
4. Open the UI.
5. Select "check rotation order" button.
6. Select rotation order required.
    - The tool will disable the viewport, change the rotation order and ensure the same rotation order is maintained.

Alternatively, the "check rotation order" feature is really helpful, however sometimes a user may want to change the rotation order for many objects at once (something the UI does not allow).
Therefore we could make a sub-menu with a list of all 6 rotation orders. Selecting object(s), then running the tool will automatically change all selected objects on all keyframes to a new rotation order.

1. Select object
2. Animate the object with default XYZ rotation order.
3. Select transform node(s)
4. Choose "ZXY" menu option (no UI)
    - The tool will disable the viewport, change the rotation order and ensure the same rotation order is maintained.

### Software Versions

- mmSolver version: v0.3.x and v0.4.x
- Maya version:  All supported.
- Operating System (OS): All supported.

**Comment by ktonegawa** [comment]
Hi David, if the MIT license of that script is compatible with the LGPL-3.0 license of this plugin and can be directly implemented/ported, I would like to take on this ticket if that is okay...

**Comment by david-cattermole** [comment]
Hey @ktonegawa, sure thing!

The tool can be directly bundled with mmSolver - that is the easiest way.

**Comment by david-cattermole** [comment]
Thanks @ktonegawa! I have made some minor changes for the copyright and license and added "..." to the menu name of the tool.

This is now pushed to the `develop_v0.3.x` branch and is ready for release in v0.3.15.
