### ISSUE TITLE
Maya 2023 support

### ISSUE THREAD

**Issue by hervus2** [david-cattermole/mayaMatchMoveSolver#244]
Hi there,

Is mayaMatchMoveSolver-0.4.0 working with Maya 2023?
Following the Maya 2022 installation process, it seems that I cannot load the solver by using the MEL command: mmsolver_load

Thanks

**Comment by david-cattermole** [comment]
Hello @hervus2,

Yes, Maya 2023 is supported on both Linux and Windows. Can you please confirm if you are on Windows or Linux?

Can you please confirm you have the following file in the exact same location on your computer...

On Windows:
`C:\Users\<Your User Name>\My Documents\maya\2023\modules\modules\mayaMatchMoveSolver-0.4.0-maya2023-win64.mod`

Or on Linux:
`~/maya/2023/modules/mayaMatchMoveSolver-0.4.0-maya2023-linux.mod`

If the file is not in that location, and you do not have a folder next to it (named `mayaMatchMoveSolver-0.4.0-maya2023-win64` or `mayaMatchMoveSolver-0.4.0-maya2023-linux` depending on your operating system), Maya will not be able to find the plug-in.

There are some instructions here for how to install the tool:
https://david-cattermole.github.io/mayaMatchMoveSolver/download.html#installation

Thanks,
David

**Comment by hervus2** [comment]
Hey David,

Thanks for your answer.
I do use Windows. It's just that when downloading the zip file, it doesn't match "mayaMatchMoveSolver-0.4.0-maya2023-win64.mod"! That's I think the issue I'm facing. Downloading the file from the link you provided seems to match...

Many thanks

**Comment by david-cattermole** [comment]
That's good to hear. It sounds like you've got it working(?), I'm going to close this issue, but if it's still not working re-open the issue and let me know.

**Comment by hervus2** [comment]
All is good now!
Just need to figure out how to use the Line tools to calibrate a camera! Do you have any video about that?

Cheers

**Comment by david-cattermole** [comment]
Unfortunately there is no video tutorial, however camera calibration tools documentation can be found here:
https://david-cattermole.github.io/mayaMatchMoveSolver/tools_linetools.html#tool-usage

You need to create a Calibration set up with the `mmSolver > Line Tools > Create Camera Calibration Setup` menu button.
Select the "mmImagePlane1" node and set the image to point to your image(s).
Then set your lines based on the parallel lines in the shot.
Move the "origin_point" to the intended origin. 
Lastly use `mmSolver > Line Tools > Update Camera Calibration` menu button to calculate the camera orientation.

Assuming your lines are long enough you can also solve some lens distortion.
Select the lines nodes in the outliner and use the [Subdivide Line](https://david-cattermole.github.io/mayaMatchMoveSolver/tools_linetools.html#subdivide-line) tool to add more Markers to define the line. Move the Markers to match the straight edges in your image and repeat by adding more Markers as needed.
Use the [Camera Context Menu](https://david-cattermole.github.io/mayaMatchMoveSolver/tools_cameracontextmenu.html) to add a lens to your camera.
Then open the Solver UI and add the Lines you want to solve with to the "Input Objects".
Add the lens distortion attributes (in the channel box) to the Solver UI "Output Attributes".
Switch to the Standard solver and press "Solve".
After the lens distortion is solved you may need to use `mmSolver > Line Tools > Update Camera Calibration` to update the camera again with the straightened lines.

Does that make sense?

**Comment by hervus2** [comment]
Thanks for the explanations. I will try that and maybe open a new topic to be easily found by others if needed! :)
Cheers
