### ISSUE TITLE
SurfaceCluster tool Error

### ISSUE THREAD

**Issue by StanleyBalu** [david-cattermole/mayaMatchMoveSolver#250]
### Problem or Feature
I downloaded the latest MM solver. the surface cluster tool is throwing an error that the module could not be found. It looks like the folder is missing the __init__ file. It worked when I created it manually.

### Software Versions
Maya 2020

- mmSolver version: 0.4.8

- Maya version: 2020

[Maya version number or print out here]

Maya Version: Autodesk Maya 2020
Maya API: 20200000
Qt Version: 5.12.5
Compositing Manager: True
Window Manager: Windows Aero
GPU:   Version : 2016.11.53.12. Feature Level 5.
  Adapter : NVIDIA GeForce RTX 3060/PCIe/SSE2
  Vendor ID: 4318. Device ID : 9476
  Driver : .
  API : OpenGL V.4.6.
  Max texture size : 16384 * 16384.
  Max tex coords : 32
  Shader versions supported (Vertex: 5, Geometry: 5, Pixel 5).
  Shader compiler profile : (Best card profile)
  Active stereo support available : 0
  GPU Memory Limit : 12288 MB.
  CPU Memory Limit: 31058.9 MB.

- Operating System (OS): Windows

**Comment by david-cattermole** [comment]
Dang! Thanks for letting me know @StanleyBalu, I'll fix and release ASAP.

**Comment by david-cattermole** [comment]
@StanleyBalu this is now released in v0.4.9.
