### ISSUE TITLE
Maya Generation of 3D positions from 2D screen-space positions

### ISSUE THREAD

**Issue by IceSean** [david-cattermole/mayaMatchMoveSolver#257]
Hello, how to get a 3D locator position in the same position in different frames in the camera view in Maya?
I used a tool before. In the Maya camera view, click the tool and click the same position in two frames. A locator will be generated, and then this locator will always be at that position during the entire camera movement.
This problem has puzzled me for a long time. Thanks

**Comment by david-cattermole** [comment]
Hello @IceSean,

You can use the Triangulate Bundle tool to calculate the 3D position of a bundle from a Marker on two different frames (as viewed through a camera):
https://david-cattermole.github.io/mayaMatchMoveSolver/tools_bundletools.html#triangulate-bundle

For example:
1) Create a Marker in a (translating) camera.
2) Set the position of the Marker to same "feature" in the image on two different frames.
3) Run the Triangulate Bundle tool to set the Bundle translate XYZ values.

This assumes the 2 frames in the camera have parallax - nodal cameras will not work.

If you have other questions I'd recommend joining the Google Group where you can ask these questions and get answers from other users of mmSolver:
https://groups.google.com/forum/#!forum/maya-matchmove-solver

Thanks,
David
