### ISSUE TITLE
Maya Tools - Enable/disable Hold-Outs

### ISSUE THREAD

**Issue by bpatchasaheb** [david-cattermole/mayaMatchMoveSolver#260]
###  Feature
Need maya tools to enable/disable hold-outs for selected/all meshes.
Tools should be able to set enable/disable hold-out state of meshes.

**Comment by david-cattermole** [comment]
This is being addressed as part of PR #265.

**Comment by david-cattermole** [comment]
This has been merged and will be released in v0.5.0-beta4.
