### ISSUE TITLE
Maya Tools - Viewport toggle visibility

### ISSUE THREAD

**Issue by bpatchasaheb** [david-cattermole/mayaMatchMoveSolver#263]
### Feature

Need tools to toggle visibility of node types such as polygons, locators etc in viewport.

Viewport.py from utils already has code to get and set visibility. 
We need to find a better way to handle this.

**Comment by david-cattermole** [comment]
The last change is done now; Markers, Bundles, Curves and Locators are toggled with the "[toggleviewportctrls](https://github.com/david-cattermole/mayaMatchMoveSolver/tree/master/python/mmSolver/tools/toggleviewportctrls)" tool.

Closing.

This will be available in the next v0.5.0-beta release and then v0.5.0.
