### ISSUE TITLE
Add Maya 2018 Linux - support please

### ISSUE THREAD

**Issue by por4por** [david-cattermole/mayaMatchMoveSolver#47]
Could someone please compile the maya 2018 for lixux?

Thank you!

**Comment by david-cattermole** [comment]
Hello por4por,

Unfortunately I am not able to compile for Maya 2018 on Linux myself. It is something I am trying to do, but do not have the resources. I have been informed that mmSolver does run well on Maya 2018 on Linux.

However compiling the plug-in on Linux is quite easy (much easier than on Windows). Please follow the instructions in "BUILD.md" inside the .tar.gz latest release (currently v0.1.1):

https://github.com/david-cattermole/mayaMatchMoveSolver/releases/tag/v0.1.1

**Comment by por4por** [comment]
Thank you for that info. 

And thank you for this release 

Jarrod

**Comment by david-cattermole** [comment]
After doing some more research, I believe it will be possible for me to build with Maya 2018 on Linux.

I haven't confirmed yet, but I'd expect the next release (due in a week or two) to have a compiled version for Maya 2018 on Linux.

**Comment by por4por** [comment]
That would be fantastic! Thank you.

*Jarrod*

**Comment by david-cattermole** [comment]
Hi Jarrod,

Maya 2018 Linux support has been added to the latest "master" branch, and documentation updated.
I understand the new release is not yet finished but will be released in the next few days.

For now I believe we can close this issue.

**Comment by david-cattermole** [comment]
Hello Jarrod,

This is now released:
https://github.com/david-cattermole/mayaMatchMoveSolver/releases/tag/v0.2.0

Let us know if this works for you.

David
