### ISSUE TITLE
Maya Tool - Solver UI - Add Attributes with no selected channel box attributes should add "default" attributes

### ISSUE THREAD

**Issue by david-cattermole** [david-cattermole/mayaMatchMoveSolver#48]
When a user selects a node, but does not select any attributes in the channel box, a default set of attributes should be added.

The default set of attributes from a node is dependent on the type of node detected.

- For a Bundle node, the translateX, Y and Z should be added.
- For a Camera, the Translate X, Y, Z, Rotate X, Y, Z (and possibly focal length) should be added.
- For a regular transform node, Translate X, Y, Z, Rotate X, Y and Z will be added, unless they are hidden from the channel box (which would be common on a rig control).

**Comment by anilreddy24fps** [comment]
Wonderful,  this will be a good update to UI, Thanks David!

**Comment by david-cattermole** [comment]
This is now added to the master branch and will be released in v0.2.0.
