### ISSUE TITLE
Maya Tool - Solver UI - User settable Min/Max values for Attributes

### ISSUE THREAD

**Issue by david-cattermole** [david-cattermole/mayaMatchMoveSolver#65]
The Solver UI should display the current min/max values for each attribute listed UI.
Users must also be able to change the min/max values with the UI.

Users cannot set min/max values past the "physical limitations" of Maya attributes, and these should be set as min/max values in the UI.

Usage:
1) Open Solver UI
2) Select Node Attributes in Maya
3) Add Node Attributes to Solver UI with "+" button.
4) Double-click on "Min" or "Max" field.
5) Type a value and press enter.
6) The field is now saved on the active Collection for that node and attribute. If the attribute is removed and then added back to the Collection the min/max value will be remembered. 

This issue is related to #64.

**Comment by david-cattermole** [comment]
It should also be possible to specify a dynamic attribute "range".

For example, an Attribute is set to 42.0 and the user sets a "range" of "1.0". This will automatically add a min value of 41.0 and a max value of 43.0. After the solve has finished, lets say the attribute has solved to 42.5. Now when the user solves again, the min/max values will be added as 41.5 and 43.5.

This will allow a user to narrow an Attribute down and not allow it to move much, per-solve, but allow other attributes freedom to change.

**Comment by david-cattermole** [comment]
An interesting use case for the "range" feature is if the attribute is already animated.

If an attribute is already animated and a "range" of +/- 1.0 is given, what is the min/max value if the attribute animates from 42.0 at start frame to 52.0 end frame? 

Should the range be calculated from the min/max values of the animation curves? Or should the current frame's min/max value be used when the user sets the range?

These are questions to answer when we implemente this feature.

**Comment by StanleyBalu** [comment]
Hi David

I think having min and max value and resolving the existing animated curve will work better.

-Stanley

**Comment by david-cattermole** [comment]
Hi Stanley,

You make a good point, I'll focus on the min/max value functionality first.
Later we can decide of any "range" feature would be helpful or how it should be used - we'll have a better idea once min/max values are used.

David

**Comment by david-cattermole** [comment]
A "Set Attribute Details" UI has been committed, allowing users to set min/max values on a per-attribute, per-collection basis. 

This tool can be used by selecting a node (and optionally the attributes in the Channel Box) and using the shelf button. A right-click "Edit Details..." menu item has been added to the Solver UI, but is currently not working correctly. This is a problem still needing to be addressed.

Also, brand new constraints have been added to the solver; Smoothness and Stiffness. These constraints can be used to ensure that per-frame animated attribute solving maintains a "smooth" or "stiff" curve value.

"Smoothness" means that the curve will not drastically jump from frame to frame.
"Stiffness" means that the curve will stay flat.

Both these new constraints, including the min/max values are optional. See the documentation for more detail on this.

**Comment by david-cattermole** [comment]
The last known bugs have been fixed. 

This issue is considered finished and has been merged into the `develop` branch.
This feature will be released in the next version of mmSolver; v0.3.4.

More testing will be performed and if bugs are found relating to this feature a new issue will be created.
