### ISSUE TITLE
Solver warning - when we have static output attributes and solving for current frame 

### ISSUE THREAD

**Issue by anilreddy24fps** [david-cattermole/mayaMatchMoveSolver#68]
Solver is throwing warning if I have static output attributes while solving for current frame only, and solver refuses to solve.

Below is the warning when is printing in the script editor.

"// Warning: mmSolver.tools.solver.lib.collection : Cannot execute solver, collection is not valid.collection=<mmSolver._api.collection.Collection object at 0x0000014B369EBF28>"

Attaching a screen shot below.
![54799450_321389558562209_6500835677154836480_n](https://user-images.githubusercontent.com/31835170/54858258-aa855580-4d53-11e9-9d43-c77054004101.jpg)

Thanks
Anil Reddy

**Comment by david-cattermole** [comment]
Thanks Anil.

I believe I've now fixed this bug in the latest master branch. Commit 2ddfadb.

The Solver Step strategy will automatically change to 'per-frame' as well as changing the frames to "CURRENT". I have also disabled editing of those fields while "Override Current Frame" is checked on, to stop users from potentially breaking the Solver Steps.

David
