### ISSUE TITLE
make + make install causes build to stop

### ISSUE THREAD

**Issue by maxnbk** [david-cattermole/mayaMatchMoveSolver#69]
Using latest 0.2.0 release, and building from source via CMake, on Linux, I am getting an odd issue where two things are seemingly chaining to cause an issue.
First, when running make, the entire build, including installation, runs.
Second, when running make install, the entire build rebuilds.
Third, because the build is re-running the entire build, I get stopped up when, presumably, some build-clean operation is running, and stops the build with:
`rm: remove write-protected regular file ‘CMakeFiles/3.12.4/CMakeSystem.cmake’?`
I can presumably put in some rm -rf's in the build process myself, but it seems odd and points to possibly other issues.

Altogether the configurability of the build is fantastic however, huge props.

**Comment by maxnbk** [comment]
Have tested/IDed that this PR fixes for me, at least the part where it stops in the middle of the build. The rebuilding bit is not fixed, but this lets me proceed even if things build twice for no obvious reason.
#70

**Comment by david-cattermole** [comment]
Thanks for bringing this to my attention, maxnbk.

Can I confirm a sequence of shell commands that reproduces this?

I am not able to reproduce this using the below commands. I'm not sure how PR #70 would help in this case (although I see no harm in using PR #70). 

Something like the below?
```
$ cd <project root>
$ bash scripts/build_cminpack.bash
$ bash scripts/build_qtpy.bash
$ bash scripts/build_mmSolver_linux_maya2017.bash
$ cd build
$ make
$ make install
```

Yes, the build system is fairly automatic, but there is room for improvement. For example, each time "make" is called the Qt .ui files are re-compiled, changing the timestamp - this should be addressed (eventually).

David

**Comment by maxnbk** [comment]
Looks like the rebuild thing is my fault, though the removal thing was not and still fixed the issue.
I was wrapping my build in cmake's externalProject_add and during it's own make/make-install, the build was seemingly invalidating what happened during the 'update' step (the cminpack and levmar build) and causing the higher level make install to re-eval from the bottom up, which I've address on my end.
Apologies for the confusion, though the PR merge has helped me with the other part.
Thanks!
