### ISSUE TITLE
Maya Tool - Remove All mmSolver Nodes from Scene

### ISSUE THREAD

**Issue by david-cattermole** [david-cattermole/mayaMatchMoveSolver#76]
Create a tool to clean up and delete all mmSolver specific nodes.
This will help users needing to send files to other users that do not have mmSolver.

Usage:
1) Open Maya scene with mmSolver
2) Run tool (on the mmSolver shelf)
3) All nodes specific to mmSolver are removed and the plug-in unloaded.

When working in a GUI environment and a "force=True" keyword argument is not passed, a pop-up dialog should be presented saying "Are you sure?".

This tool / function should be executable without a Maya GUI open (such as inside mayapy).

**Comment by david-cattermole** [comment]
It may also be helpful to create a user interface for this tool. 
A user may wish to remove all nodes related to mmSolver, not just custom nodes.

We could create a window to allow deleting the following categories in a Maya scene file.
- Markers
- Bundles
- Marker Groups (and Markers)
- Collections

This GUI would be a "clean up" tool. The primary use for this tool is to allow clean up of a Maya scene before giving the the Maya file to another person, who may no have mmSolver installed.

We may need to consider how nodes connected or parented under marker groups, or bundles should be handled. For example, a parented node should be unparented and baked into world space.

**Comment by ktonegawa** [comment]
Hi David, I created a Pull request from my forked repo as to start a conversation...

**Comment by david-cattermole** [comment]
Hello @ktonegawa,

Thanks for your PR, it has been merged into the master branch, and will be released in the next version.

Would you like to write some user documentation for the tool? If not, I can probably write it in the next few days.

Meanwhile I have added your name to the AUTHORS.txt file and copyrights, so your name is on the website:
https://david-cattermole.github.io/mayaMatchMoveSolver/#authors
(might take a little while to build and update)

**Comment by ktonegawa** [comment]
Thank you @david-cattermole  for merging the PR so fast! I was going to address your note about creating a `lib.py` and porting over the functions, if you would still like me to do this please let me know!

Yes I would love to take a crack at the documentation portion. Should I just try adding a section into the `tools.html` page...?

**Comment by david-cattermole** [comment]
> I was going to address your note about creating a lib.py and porting over the functions, if you would still like me to do this please let me know!

If you want to, go ahead, but I don't think it's needed.

> Yes I would love to take a crack at the documentation portion. Should I just try adding a section into the tools.html page...?

You don't edit the `tools.html` file directly, because it is auto-generated with Sphinx.

Instead, you should edit this file:
https://github.com/david-cattermole/mayaMatchMoveSolver/blob/master/docs/source/tools_generaltools.rst

Annoyingly, I cannot show you the actual code for that file via GitHub because GitHub is automatically rendering it into HTML.
You should probably add a new heading between "Reparent Under Node" and "Sort Selected Nodes In Outliner" because that is where you've placed your menu.

For future reference, I have added the sphinx auto-generated documentation in commit 6b488ac1919cfd83ba54d2f162ea512b44d66ed4 so you can see what I have changed.

**Comment by david-cattermole** [comment]
There has been some documentation added in PR #189.

The documentation is uploaded:
https://david-cattermole.github.io/mayaMatchMoveSolver/tools_generaltools.html#remove-solver-nodes
... and here,
https://david-cattermole.github.io/mayaMatchMoveSolver/mmSolver.tools.removesolvernodes.html

I think we can close this issue now, if there's a problem we'll open a new issue.

Thanks @ktonegawa!
