### ISSUE TITLE
Attribute Error while pressing center button in mmSolver shelf

### ISSUE THREAD

**Issue by anilreddy24fps** [david-cattermole/mayaMatchMoveSolver#8]
Getting a Attribute error while pressing center button in mmSolver shelf, if any object is already centered, clear the selection and press the center button its giving a below error.

# Error: AttributeError: file C:\Users\"USER"\Documents\maya\2018\modules\mayaMatchMoveSolver-0.1.1-maya2018-win64\python\mmSolver\tools\centertwodee\tool.py line 128: 'unicode' object has no attribute 'objExists'

-Anil Reddy

**Comment by david-cattermole** [comment]
Thanks Anil, this has been fixed now. It was a silly typo.
