### ISSUE TITLE
Building on Linux error in termial

### ISSUE THREAD

**Issue by anilreddy24fps** [david-cattermole/mayaMatchMoveSolver#91]
After executing "bash scripts/build_cminpack.bash"
Was getting below error in terminal

"=> bash scripts/build_cminpack.bash
Package Root: /home/anilreddy/dev/mayaMatchMoveSolver/scripts/../external/
Adding Package: cminpack-1.3.6
Downloading: http://devernay.free.fr/hacks/cminpack/cminpack-1.3.6.tar.gz
Saving Archive: /home/anilreddy/dev/mayaMatchMoveSolver/external/archives/cminpack-1.3.6.tar.gz
Unpacking: /home/anilreddy/dev/mayaMatchMoveSolver/external/archives/cminpack-1.3.6.tar.gz
Extracting: /home/anilreddy/dev/mayaMatchMoveSolver/external/working
rm: cannot remove ‘*’: No such file or directory
scripts/build_cminpack.bash: line 28: cmake: command not found
make: *** No rule to make target `clean'.  Stop.
make: *** No rule to make target `all'.  Stop.
make: *** No rule to make target `install'.  Stop.
[anilreddy@192-168-1-7 mayaMatchMoveSolver]$ 
"
Even after installing cmake manually and running next command : 
=> bash scripts/build_mmSolver_linux_maya2017.bash

Getting this following error :
"
make[3]: sphinx-build: Command not found
make[3]: *** [html] Error 127
make[2]: *** [../docs/build/html/py-modindex.html] Error 2
make[1]: *** [docs/CMakeFiles/build_documentation.dir/all] Error 2
make: *** [all] Error 2
"

OS : CentOS Linux 7

-Anil Reddy

**Comment by david-cattermole** [comment]
Hello Anil,

It looks to me like you don't have `cmake` or `sphinx` installed. These are required to build mmSolver.

The dependencies for mmSolver are listed here:
https://github.com/david-cattermole/mayaMatchMoveSolver/blob/master/BUILD.md#dependencies

I have updated the BUILD_LINUX.md documentation to include a small section specific to CentOS 7. 
https://github.com/david-cattermole/mayaMatchMoveSolver/blob/master/BUILD_LINUX.md#installing-dependencies

Running the following (as root user) under CentOS 7 should install the build dependencies:
```
yum install gcc make cmake python python-sphinx
```

Please let me know if it works.

Good luck,
David

**Comment by david-cattermole** [comment]
Hi Anil,

Can you confirm this fixes the problem?

David

**Comment by anilreddy24fps** [comment]
Hi David,
I ran following command inside terminal and then following linux build instructions worked for me 

> "yum install gcc make cmake python python-sphinx"

I can confirm its working!

-Anil Reddy

**Comment by david-cattermole** [comment]
Fantastic! The documentation now has this information. Thanks for pointing it out, I'm sure new users will find it helpful.
